#!/bin/sh

systemctl_global() {
    systemctl --user --global $*
}

systemctl_users() {
    for user in $(loginctl list-users | tail -n "+2" | head -n "-2" | awk '{print $2}' | sort -u); do
        su $user -c "systemctl --user $*"
    done
}

systemctl_active_users() {
    for user in $(loginctl list-sessions | tail -n "+2" | head -n "-2" | awk '{print $3}' | sort -u); do
        su $user -c "systemctl --user $*"
    done
}

systemctl_all() {
    systemctl_global $*
    ret=$?
    systemctl_users $*
    return $ret
}

systemctl daemon-reload
systemctl_active_users daemon-reload

echo "Disabling default ssh-agent and enabling ssh-tpm-agent..."

(systemctl_all disable ssh-agent.socket ssh-agent.service >/dev/null 2>&1 && systemctl_active_users stop ssh-agent.socket ssh-agent.service >/dev/null 2>&1) || true
(systemctl_all disable gcr-ssh-agent.socket gcr-ssh-agent.service >/dev/null 2>&1 && systemctl_active_users stop gcr-ssh-agent.socket gcr-ssh-agent.service >/dev/null 2>&1) || true

systemctl_all enable ssh-default-agent.service ssh-tpm-agent.service >/dev/null 2>&1 || true
systemctl_active_users restart ssh-default-agent.service ssh-tpm-agent.service >/dev/null 2>&1
