#!/bin/sh

systemctl_global() {
    systemctl --user --global $*
}

systemctl_users() {
    for user in $(loginctl list-users | tail -n "+2" | head -n "-2" | awk '{print $2}' | sort -u); do
        su $user -c "systemctl --user $*"
    done
}

systemctl_active_users() {
    for user in $(loginctl list-sessions | tail -n "+2" | head -n "-2" | awk '{print $3}' | sort -u); do
        su $user -c "systemctl --user $*"
    done
}

systemctl_all() {
    systemctl_global $*
    ret=$?
    systemctl_users $*
    return $ret
}

echo "Disabling ssh-tpm-agent and re-enabling default ssh-agent..."

systemctl_all disable ssh-default-agent.service ssh-tpm-agent.service >/dev/null 2>&1 || true
systemctl_active_users stop ssh-default-agent.service ssh-tpm-agent.service >/dev/null 2>&1 || true

(systemctl_all enable gcr-ssh-agent.socket gcr-ssh-agent.service >/dev/null 2>&1 && systemctl_active_users restart gcr-ssh-agent.socket gcr-ssh-agent.service >/dev/null 2>&1) || (systemctl_all enable ssh-agent.socket ssh-agent.service >/dev/null 2>&1 && systemctl_active_users restart ssh-agent.socket ssh-agent.service >/dev/null 2>&1) || true

echo "Disabling sshd-tpm-agent"

systemctl disable sshd-default-agent.service sshd-tpm-agent.service >/dev/null 2>&1 || true
systemctl stop sshd-default-agent.service sshd-tpm-agent.service >/dev/null 2>&1
