#!/bin/sh
set -e

PREREQ=""
prereqs() {
    echo "${PREREQ}"
}
case "${1}" in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

echo ${WIRELESS_MODULES} >/dev/stderr
echo ${WIRELESS_MODULES} >/dev/stdout

manual_add_modules ${WIRELESS_MODULES}
copy_exec /sbin/wpa_supplicant
copy_exec /sbin/wpa_cli

cat >/tmp/initramfs-wpa_supplicant.conf <<EOF
ctrl_interface=/tmp/initram-wpa_supplicant

network={
    ssid="${WIRELESS_SSID}"
    scan_ssid=1
    key_mgmt=WPA-PSK
    psk="${WIRELESS_PASSWORD}"
}
EOF
copy_file config /tmp/initramfs-wpa_supplicant.conf /etc/wpa_supplicant.conf
rm /tmp/initramfs-wpa_supplicant.conf
