#!/bin/sh
set -e

PREREQ=""
prereqs() {
    echo "${PREREQ}"
}
case "${1}" in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules ${WIRELESS_MODULES}
copy_exec /sbin/wpa_supplicant
copy_exec /sbin/wpa_cli
# copy_file config /etc/initramfs-tools/wpa_supplicant.conf /etc/wpa_supplicant.conf
