#!/bin/sh
set -e
set -o pipefail

PREREQ=""

if [ -f "$(dirname $(realpath $0))/stop-openssh" ]; then
    PREREQ="${PREREQ} stop-openssh"
fi

prereqs() {
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

error_func() {
    echo "kill-wireless script failed"
    sleep 3
}

main() {
    . /scripts/wireless.conf

    if grep -qw "wireless" /proc/cmdline; then
        if [ -e /run/initram-wpa_supplicant.pid ]; then
            echo "Killing wireless"

            kill $(cat /run/initram-wpa_supplicant.pid)

            rm -rf /run/initram-wpa_supplicant_interface
            rm -f /run/initram-wpa_supplicant.pid

            echo "Killed wireless"
        fi
    fi
}

main $* || error_func
