#!/bin/sh
set -e

PREREQ="stop-openssh"
prereqs() {
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
. /scripts/wireless.conf

if grep -qw "wireless" /proc/cmdline; then
    echo "Killing wireless"
    kill $(cat /run/initram-wpa_supplicant.pid)

    rm -rf /run/initram-wpa_supplicant_interface
    rm -f /run/initram-wpa_supplicant.pid
fi
