#!/bin/sh
set -e

PREREQ=""
prereqs() {
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

echo ""
log_success_msg "Killing wireless"
kill $(cat /run/initram-wpa_supplicant.pid)
