#!/bin/sh
set -e
set -o pipefail

PREREQ=""

if [ -f "$(dirname $(realpath $0))/enable-wireless" ]; then
    PREREQ="${PREREQ} enable-wireless"
fi

prereqs() {
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

error_func() {
    echo "start-openssh script failed"
    panic
}
if ! echo "$*" | grep -qw "trapped"; then
    $0 $* trapped || error_func
    exit 0
fi

. /scripts/functions
. /scripts/openssh.conf

if grep -qw "openssh" /proc/cmdline; then
    echo "Starting OpenSSH server on ${OPENSSH_PORTS}"

    mkdir -p /run/sshd
    chown root:root -R /run/sshd

    IFS=','
    ports=
    for port in ${OPENSSH_PORTS}; do
        ports="$ports -p $port"
    done

    IFS=' '
    keys=
    for file in /etc/ssh/ssh_host_*key; do
        keys="$keys -h $file "
    done

    /sbin/sshd -D -o PidFile=/run/initram-openssh.pid $ports -f /etc/ssh/sshd_config $keys &
    echo "Started OpenSSH server"
fi
