#!/bin/sh
set -e
set -o pipefail

PREREQ=""
prereqs() {
    echo "${PREREQ}"
}
case "${1}" in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

error_func() {
    echo "wireless hook failed"
    sleep 1
    exit 1
}

main() {
    copy_file config /etc/initramfs-tools/conf.d/wireless /scripts/wireless.conf

    if [ -n "${WIRELESS_MODULES}" ]; then
        manual_add_modules ${WIRELESS_MODULES}
    fi
    copy_exec /sbin/wpa_supplicant
    copy_exec /sbin/wpa_cli

    cat >/tmp/initramfs-wpa_supplicant.conf <<EOF
ctrl_interface=/run/initram-wpa_supplicant_interface

network={
    ssid="${WIRELESS_SSID}"
    scan_ssid=1
    key_mgmt=WPA-PSK
    psk="${WIRELESS_PASSWORD}"
}
EOF
    copy_file config /tmp/initramfs-wpa_supplicant.conf /etc/wpa_supplicant.conf
    rm /tmp/initramfs-wpa_supplicant.conf
}

main $* || error_func
