#!/bin/sh
set -e
set -o pipefail

PREREQ=""
prereqs() {
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

error_func() {
    echo "stop-openssh script failed"
    sleep 3
}

main() {
. /scripts/openssh.conf

if grep -qw "openssh" /proc/cmdline; then
    echo "Killing OpenSSH"

    pid=$(cat /run/initram-openssh.pid)
    kill ${pid} $(ps -eo ppid,pid | grep -E "^[ \t]*${pid}[ \t]+" | awk '{ print $2 }')

    rm -f /run/initram-openssh.pid

    echo "Killed OpenSSH"
fi
}

main $* || error_func
