#!/bin/sh
set -e
set -o pipefail

PREREQ=""
prereqs() {
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

error_func() {
    echo "stop-openssh script failed"
    sleep 3
}
if ! echo "$*" | grep -qw "trapped"; then
    $0 $* trapped || error_func
    exit 0
fi

. /scripts/functions
. /scripts/openssh.conf

if grep -qw "openssh" /proc/cmdline; then
    if [ -f /run/initramfs-openssh.pid ]; then
        echo "Killing OpenSSH"
        kill $(cat /run/initram-openssh.pid)

        rm -f /run/initram-openssh.pid

        echo "Killed OpenSSH"
    fi
fi
