#!/bin/sh
set -e

PREREQ=""
prereqs() {
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
. /scripts/wireless.conf

AUTH_LIMIT=30

if grep -qw "wireless" /proc/cmdline; then
    WPA_COMMAND="/sbin/wpa_cli -p /run/initram-wpa_supplicant_interface -i ${WIRELESS_INTERFACE}"

    echo "Starting wireless connection on ${WIRELESS_INTERFACE}"
    /sbin/wpa_supplicant -B -i ${WIRELESS_INTERFACE} -c /etc/wpa_supplicant.conf -P /run/initram-wpa_supplicant.pid -f /tmp/initram-wpa_supplicant.log

    limit=${AUTH_LIMIT}
    echo "Waiting for connection (max ${AUTH_LIMIT} seconds)"
    while [ $limit -ge 0 -a "$($WPA_COMMAND status | grep wpa_state)" != "wpa_state=COMPLETED" ]; do
        echo $($WPA_COMMAND status | grep wpa_state)
        sleep 1
        # echo -n "."
        limit=$(expr $limit - 1)
    done
    echo ""

    if [ "$($WPA_COMMAND status | grep wpa_state)" != "wpa_state=COMPLETED" ]; then
        export ONLINE=0
        echo "Wireless offline after timeout"
        panic
    else
        export ONLINE=1
        echo "Wireless online"
    fi
    echo $($WPA_COMMAND status | grep wpa_state)

    configure_networking

    echo "Wireless configured"
fi
