#!/bin/sh
set -e

PREREQ="enable-wireless"
prereqs() {
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
. /scripts/openssh.conf

if grep -qw "openssh" /proc/cmdline; then
    if grep -qw "wireless" /proc/cmdline; then
        echo "Starting OpenSSH server on ${OPENSSH_PORTS}"

        mkdir -p /run/sshd
        chown root:root -R /run/sshd

        IFS=','
        ports=
        for port in ${OPENSSH_PORTS}; do
            ports="$ports -p $port"
        done

        IFS=' '
        keys=
        for file in /etc/ssh/ssh_host_*key; do
            keys="$keys -h $file "
        done

        /sbin/sshd -D -o PidFile=/run/initram-openssh.pid $ports -f /etc/ssh/sshd_config $keys &
        echo "Started OpenSSH server"
    else
        echo "OpenSSH enabled without wireless! Check your kernel parameters."
        panic
    fi
fi
