name: Build Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt install gcc g++ binutils-x86-64-linux-gnu binutils-aarch64-linux-gnu

      - name: Build
        run: |
          dpkg --help
          dpkg-buildpackage --help
          ls -la
          make build
