name: Build Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build (${{ matrix.arch }})
    runs-on: ${{ matrix.arch_tag }}
    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - arch: amd64
            arch_tag: ubuntu-24.04
          - arch: aarch64
            arch_tag: ubuntu-24.04-arm
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get install -y build-essential gcc g++ make binutils-x86-64-linux-gnu binutils-aarch64-linux-gnu debhelper

      - name: Build
        run: |
          make build
