name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish (${{ matrix.arch }})
    runs-on: ${{ matrix.arch_tag }}
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - arch: amd64
            arch_tag: ubuntu-24.04
          - arch: arm64
            arch_tag: ubuntu-24.04-arm
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get install -y build-essential gcc g++ binutils make debhelper

      - name: Build
        run: |
          make pull-ssh-tpm-agent
          make build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-${{ matrix.arch }}
          path: |
            *.changes
            *.buildinfo
            *.deb
            *.tar.gz
            *.dsc

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            *.deb
